In [1]:
!pip install gymnasium

In [2]:
import gymnasium as gym
import numpy as np
import time
from IPython import display
from gymnasium.envs.toy_text.frozen_lake import FrozenLakeEnv
from gymnasium.envs.toy_text.taxi import TaxiEnv

In [3]:
env = FrozenLakeEnv(desc=None, map_name="4x4", render_mode="ansi", is_slippery=True)
# FrozenLake8x8
# env = FrozenLakeEnv(desc=None, map_name="4x4", render_mode="ansi", is_slippery=True)
# Taxi
# env = TaxiEnv()

In [4]:
env.P[0][3] # Transition model

[(0.3333333333333333, 1, 0.0, False),
 (0.3333333333333333, 0, 0.0, False),
 (0.3333333333333333, 0, 0.0, False)]

In [5]:
env.observation_space.n

np.int64(16)

In [6]:
env.action_space.n

np.int64(4)

In [7]:
def play(env, policy, render=False):
    state, _ = env.reset()
    total_reward = 0
    steps = 0
    done = False
    while not done:
        action = policy[state]
        next_state, reward, done, info, _ = env.step(action)
        total_reward += reward
        steps += 1
        if render:
            print(env.render())
            time.sleep(0.5)
            if not done:
                display.clear_output(wait=True)
        state = next_state

    return (total_reward, steps)

In [8]:
policy_0 = np.asarray([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
play(env, policy_0)

(0.0, 26)

In [9]:
policy_0 = np.asarray([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
play(env, policy_0, True)


  (Left)
SFFF
FHFH
FFFH
HFFG



(0.0, 13)

In [10]:
policy_1 = np.asarray([0, 1, 1, 3, 1, 0, 2, 0, 1, 1, 2, 2, 3, 3, 1, 0])
play(env, policy_1, True)

  (Up)
SFFF
FHFH
FFFH
HFFG



(0.0, 23)

In [11]:
policy_2 = np.array([1, 1, 1, 3, 0, 1, 2, 3, 1, 1, 2, 3, 2, 2, 1, 3])
play(env, policy_2, True)

  (Down)
SFFF
FHFH
FFFH
HFFG



(0.0, 8)

In [12]:
policy_3 = np.array([0, 3, 0, 3, 0, 0, 0, 0, 3, 1, 0, 0, 0, 2, 1, 0])
play(env, policy_3, True)

  (Down)
SFFF
FHFH
FFFH
HFFG



(1.0, 86)

In [13]:
def play_multiple_times(env, policy, max_episodes):
    success = 0
    list_of_steps = []
    for i in range(max_episodes):
        total_reward, steps = play(env, policy)

        if total_reward > 0:
            success += 1
            list_of_steps.append(steps)

    print(f'Number of successes: {success}/{max_episodes}')
    print(f'Average number of steps: {np.mean(list_of_steps)}')

In [14]:
policy_0 = np.asarray([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
play_multiple_times(env, policy_0, 1000)

Number of successes: 0/1000
Average number of steps: nan


/usr/local/lib/python3.11/dist-packages/numpy/_core/fromnumeric.py:3596: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.11/dist-packages/numpy/_core/_methods.py:138: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)


In [15]:
policy_1 = np.asarray([0, 1, 1, 3, 1, 0, 2, 0, 1, 1, 2, 2, 3, 3, 1, 0])
play_multiple_times(env, policy_1, 1000)

Number of successes: 57/1000
Average number of steps: 12.017543859649123


In [16]:
policy_2 = np.array([1, 1, 1, 3, 0, 1, 2, 3, 1, 1, 2, 3, 2, 2, 1, 3])
play_multiple_times(env, policy_2, 1000)

Number of successes: 118/1000
Average number of steps: 15.338983050847459


In [17]:
policy_3 = np.array([0, 3, 0, 3, 0, 0, 0, 0, 3, 1, 0, 0, 0, 2, 1, 0])
play_multiple_times(env, policy_3, 1000)

Number of successes: 777/1000
Average number of steps: 42.891891891891895


In [18]:
def policy_evaluation(env, policy, max_iters=500, gamma=0.9):
    # Initialize the values of all states to be 0
    v_values = np.zeros(env.observation_space.n)

    for i in range(max_iters):
        prev_v_values = np.copy(v_values)

        # Update the value of each state
        for state in range(env.observation_space.n):
            action = policy[state]

            # Compute the q-value of the action
            q_value = 0
            for prob, next_state, reward, done in env.P[state][action]:
                q_value += prob * (reward + gamma * prev_v_values[next_state])

            v_values[state] = q_value # update v-value

        # Check convergence
        if np.all(np.isclose(v_values, prev_v_values)):
            print(f'Converged at {i}-th iteration.')
            break

    return v_values

In [19]:
policy_0 = np.asarray([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
v_values_0 = policy_evaluation(env, policy_0)
print(v_values_0)

Converged at 0-th iteration.
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [20]:
policy_1 = np.asarray([0, 1, 1, 3, 1, 0, 2, 0, 1, 1, 2, 2, 3, 3, 1, 0])
v_values_1 = policy_evaluation(env, policy_1)
print(v_values_1)

Converged at 48-th iteration.
[0.01904157 0.01519815 0.03161906 0.02371389 0.02538879 0.
 0.06648515 0.         0.05924054 0.13822794 0.18999823 0.
 0.         0.21152109 0.56684236 0.        ]


In [21]:
np.all(v_values_1 >= v_values_0)

np.True_

In [22]:
policy_2 = np.array([1, 1, 1, 3, 0, 1, 2, 3, 1, 1, 2, 3, 2, 2, 1, 3])
v_values_2 = policy_evaluation(env, policy_2)
print(v_values_2)

Converged at 53-th iteration.
[0.02889625 0.01951972 0.03616977 0.0271268  0.04790519 0.
 0.07391985 0.         0.08288277 0.19339319 0.21022995 0.
 0.         0.35153135 0.62684674 0.        ]


In [23]:
np.all(v_values_2 >= v_values_1)

np.True_

In [24]:
policy_3 = np.array([0, 3, 0, 3, 0, 0, 0, 0, 3, 1, 0, 0, 0, 2, 1, 0])
v_values_3 = policy_evaluation(env, policy_3)
print(v_values_3)

Converged at 80-th iteration.
[0.06888666 0.06141097 0.07440714 0.05580443 0.09185068 0.
 0.11220679 0.         0.14543323 0.24749485 0.29961611 0.
 0.         0.37993438 0.63901935 0.        ]


In [25]:
np.all(v_values_3 >= v_values_2)

np.True_

In [26]:
def value_iteration(env, max_iters=500, gamma=0.9):
    # initialize
    v_values = np.zeros(env.observation_space.n)

    for i in range(max_iters):
        prev_v_values = np.copy(v_values)

        # update the v-value for each state
        for state in range(env.observation_space.n):
            q_values = []

            # compute the q-value for each action that we can perform at the state
            for action in range(env.action_space.n):
                q_value = 0
                # loop through each possible outcome
                for prob, next_state, reward, done in env.P[state][action]:
                    q_value += prob * (reward + gamma * prev_v_values[next_state])

                q_values.append(q_value)

            # select the max q-values
            best_action = np.argmax(q_values)
            v_values[state] = q_values[best_action]

        # check convergence
        if np.all(np.isclose(v_values, prev_v_values)):
            print(f'Converged at {i}-th iteration.')
            break

    return v_values

In [27]:
optimal_v_values = value_iteration(env, max_iters=500, gamma=0.9)

Converged at 79-th iteration.


In [28]:
optimal_v_values

array([0.06888615, 0.06141054, 0.07440682, 0.05580409, 0.09185022,
       0.        , 0.11220663, 0.        , 0.14543286, 0.2474946 ,
       0.29961593, 0.        , 0.        , 0.3799342 , 0.63901926,
       0.        ])

In [29]:
def policy_extraction(env, v_values, gamma=0.9):
    # initialize
    policy = np.zeros(env.observation_space.n, dtype=np.int32)

    # loop through each state in the environment
    for state in range(env.observation_space.n):
        q_values = []
        # loop through each action
        for action in range(env.action_space.n):
            q_value = 0
            # loop each possible outcome
            for prob, next_state, reward, done in env.P[state][action]:
                q_value += prob * (reward + gamma * v_values[next_state])

            q_values.append(q_value)

        # select the best action
        best_action = np.argmax(q_values)
        policy[state] = best_action

    return policy

In [30]:
optimal_policy = policy_extraction(env, optimal_v_values, gamma=0.9)

In [31]:
optimal_policy

array([0, 3, 0, 3, 0, 0, 0, 0, 3, 1, 0, 0, 0, 2, 1, 0], dtype=int32)

In [32]:
play(env, optimal_policy, True)

  (Left)
SFFF
FHFH
FFFH
HFFG



(0.0, 49)

In [33]:
play_multiple_times(env, optimal_policy, 1000)

Number of successes: 757/1000
Average number of steps: 44.02642007926024


In [34]:
def policy_iteration(env, max_iters=500, gamma=0.9):
    # initialize
    policy = np.random.choice(env.action_space.n, size=(env.observation_space.n))

    for i in range(max_iters):
        prev_policy = policy.copy()

        v_values = policy_evaluation(env, policy, gamma=gamma)

        for state in range(env.observation_space.n):
            q_values = []

            for action in range(env.action_space.n):
                q_value = 0
                for prob, next_state, reward, done in env.P[state][action]:
                    q_value += prob * (reward + gamma * v_values[next_state])
                q_values.append(q_value)

            policy[state] = np.argmax(q_values)

        # check convergence
        if np.array_equal(policy, prev_policy):
            print(f'Converged at {i}-th iteration.')
            break

    return policy

##Thực nghiệm

In [35]:
results_time = {}

In [36]:
# FrozenLake 4x4
env = FrozenLakeEnv(desc=None, map_name="4x4", render_mode="ansi", is_slippery=True)
env_name = "FrozenLake 4x4"

# Value Iteration
start_vi = time.time()
vi_values = value_iteration(env)
vi_policy = policy_extraction(env, vi_values)
end_vi = time.time()

play_multiple_times(env, vi_policy, 1000)

# Policy Iteration
start_pi = time.time()
pi_policy = policy_iteration(env)
end_pi = time.time()

play_multiple_times(env, pi_policy, 1000)

results_time[env_name] = {
    'Value Iteration': end_vi - start_vi,
    'Policy Iteration': end_pi - start_pi
}

Converged at 79-th iteration.
Number of successes: 770/1000
Average number of steps: 44.74415584415584
Converged at 23-th iteration.
Converged at 57-th iteration.
Converged at 79-th iteration.
Converged at 80-th iteration.
Converged at 3-th iteration.
Number of successes: 787/1000
Average number of steps: 43.90851334180432


In [37]:
#FrozenLake 8x8
env = FrozenLakeEnv(desc=None, map_name="8x8", render_mode="ansi", is_slippery=True)
env_name = "FrozenLake 8x8"

# Value Iteration
start_vi = time.time()
vi_values = value_iteration(env)
vi_policy = policy_extraction(env, vi_values)
end_vi = time.time()

play_multiple_times(env, vi_policy, 1000)

# Policy Iteration
start_pi = time.time()
pi_policy = policy_iteration(env)
end_pi = time.time()

play_multiple_times(env, pi_policy, 1000)

results_time[env_name] = {
    'Value Iteration': end_vi - start_vi,
    'Policy Iteration': end_pi - start_pi
}

Converged at 117-th iteration.
Number of successes: 737/1000
Average number of steps: 72.81546811397558
Converged at 23-th iteration.
Converged at 38-th iteration.
Converged at 92-th iteration.
Converged at 90-th iteration.
Converged at 92-th iteration.
Converged at 95-th iteration.
Converged at 100-th iteration.
Converged at 112-th iteration.
Converged at 117-th iteration.
Converged at 8-th iteration.
Number of successes: 740/1000
Average number of steps: 75.07567567567567


In [38]:
#Taxi
env = TaxiEnv()
env_name = "Taxi"

# Value Iteration
start_vi = time.time()
vi_values = value_iteration(env)
vi_policy = policy_extraction(env, vi_values)
end_vi = time.time()

play_multiple_times(env, vi_policy, 1000)

# Policy Iteration
start_pi = time.time()
pi_policy = policy_iteration(env)
end_pi = time.time()

play_multiple_times(env, pi_policy, 1000)

results_time[env_name] = {
    'Value Iteration': end_vi - start_vi,
    'Policy Iteration': end_pi - start_pi
}

Converged at 116-th iteration.
Number of successes: 1000/1000
Average number of steps: 13.114
Converged at 92-th iteration.
Converged at 89-th iteration.
Converged at 100-th iteration.
Converged at 101-th iteration.
Converged at 102-th iteration.
Converged at 103-th iteration.
Converged at 105-th iteration.
Converged at 106-th iteration.
Converged at 110-th iteration.
Converged at 111-th iteration.
Converged at 111-th iteration.
Converged at 112-th iteration.
Converged at 115-th iteration.
Converged at 116-th iteration.
Converged at 116-th iteration.
Converged at 116-th iteration.
Converged at 116-th iteration.
Converged at 116-th iteration.
Converged at 17-th iteration.
Number of successes: 1000/1000
Average number of steps: 13.145


In [39]:
results_time

{'FrozenLake 4x4': {'Value Iteration': 0.03148221969604492,
  'Policy Iteration': 0.016881942749023438},
 'FrozenLake 8x8': {'Value Iteration': 0.15563178062438965,
  'Policy Iteration': 0.13966608047485352},
 'Taxi': {'Value Iteration': 0.6692607402801514,
  'Policy Iteration': 1.16426682472229}}

##Nhận xét

In [40]:
# Trong các môi trường như FrozenLake và Taxi, cả hai thuật toán đều hội tụ tốt.
# Tuy nhiên, Value Iteration thường cho kết quả nhanh hơn về mặt thời gian chạy trung bình.
# Policy Iteration có thể hội tụ trong ít iteration hơn, nhưng mỗi vòng lặp tốn nhiều chi phí hơn do phải đánh giá chính sách toàn bộ.
# Với môi trường nhỏ (4x4), Policy Iteration có thể cho kết quả tốt hơn một chút.
# Nhưng khi tăng độ phức tạp (8x8, Taxi), Value Iteration cho kết quả ổn định và nhanh hơn.

# Tổng kết: Value Iteration thường hiệu quả hơn về thời gian trong các toy environments.